### ISSUE TITLE
Console errors when viewing old posts/tweets

### ISSUE THREAD

**Issue by ErwinAI** [t3dotgg/paycheck-extension#6]
Can't grab the view count and so we get some console errors when tweet/post is before ~feb 2023?

Gotta do some checks to prevent that.

**Comment by Samathingamajig** [comment]
Fixed in #13

**Comment by ErwinAI** [comment]
Cool, thank you @Samathingamajig! Closing this.

**Comment by siddheshkothadi** [comment]
@ErwinAI I've checked and the issue still persists with the latest code. My [pull request](https://github.com/t3dotgg/paycheck-extension/pull/8#issuecomment-1672552509) with the relevant changes isn't merged yet.
